### ISSUE TITLE
Unable to save address - getting error

### ISSUE THREAD

**Issue by vivek4321** [AquilaCMS/AquilaCMS#213]
![image](https://user-images.githubusercontent.com/11358715/220251370-e36f3e90-18f1-4fa6-8560-1fdc9fde4331.png)

**Comment by devaquila** [comment]
Thank you for pointing out this error!
We have fix it in this commit:
https://github.com/AquilaCMS/AquilaCMS/commit/bf4bf07cb85cd4e88b5d5aa1e6a1af2eb7d30451

The new Aquila release includes this fix.

Enjoy
