### ISSUE TITLE
AquilaCMS don't start on NodeJS > 17

### ISSUE THREAD

**Issue by bertrand-ns** [AquilaCMS/AquilaCMS#215]
During Aquila startup, the following error occur :

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
```

According to the documentation of Node JS (https://nodejs.org/en/blog/release/v17.0.0#openssl-3-0), by default only OpenSSL 3.0 is supported.

While waiting for a fix, you can fix it by setting `NODE_OPTIONS` to `--openssl-legacy-provider`

**Comment by MaelVB** [comment]
This error is no longer present in recent versions of NodeJS (tested with version 18.16.x)
