### ISSUE TITLE
AquilaCMS installation

### ISSUE THREAD

**Issue by nextrie** [AquilaCMS/AquilaCMS#4]
When I am installing Aquila, on the configuration page, when validating after filling all fields, i get an error:
```
Please take a look on the following fields :
- MongoDB needs database name
```

I first thought it would be something to configure manually in the config json, but after looking at the templates, none of the content seems linked to mongo.
Going to `localhost:27017/` (mongodb path) shows that mongodb is up and waiting for instructions.

Any help would be great,
Have a nice day !

**Comment by AquilaCMS** [comment]
Hello,
Thanks for your feedback.

I guess the name of your database is missing, eg "mybasename".
In the input "Connection string", you can enter the value :
mongodb://localhost:27017/mybasename

We'll might add a "Test" button to check the connection to the database.
